# Run the RISC-V riscv-arch-test test framework port to check current NEORV32 version

name: 'riscv-arch-test'

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
        - I
        - C
        - M
        - privilege
        - Zifencei
    name: 'RISC-V Compatibility Check'

    steps:

    - name: '🧰 Repository Checkout'
      uses: actions/checkout@v2

    - name: '🚧 Run RISC-V Architecture Tests'
      uses: docker://ghcr.io/stnolting/neorv32/sim
      with:
        args: ./do.py RunRISCVArchitectureTests -s ${{ matrix.suite }}
